import { Repository } from './workspace-manager.js';
import { CrossRepoAnalysis, CrossRepoDependency } from './cross-repo-analyzer.js';

export class CrossRepoDocGenerator {
  
  /**
   * Generate comprehensive cross-repository documentation
   */
  generateCrossRepoDocumentation(analysis: CrossRepoAnalysis): string {
    const currentDate = new Date().toISOString().split('T')[0];
    let doc = '';
    
    // Header
    doc += `# Cross-Repository Workflow Documentation\n\n`;
    doc += `> **Workspace Analysis Report**\n\n`;
    doc += `**Workspace:** \`${analysis.workspace}\`\n`;
    doc += `**Generated:** ${currentDate}\n`;
    doc += `**Repositories Analyzed:** ${analysis.repositories.length}\n\n`;
    
    doc += `---\n\n`;
    
    // Table of Contents
    doc += `## 📋 Table of Contents\n\n`;
    doc += `1. [Repository Overview](#repository-overview)\n`;
    doc += `2. [Architecture Diagram](#architecture-diagram)\n`;
    doc += `3. [Cross-Repository Dependencies](#cross-repository-dependencies)\n`;
    doc += `4. [Shared Packages](#shared-packages)\n`;
    doc += `5. [Integration Patterns](#integration-patterns)\n`;
    doc += `6. [Tech Stack Summary](#tech-stack-summary)\n`;
    doc += `7. [Development Workflow](#development-workflow)\n`;
    doc += `8. [Recommendations](#recommendations)\n\n`;
    
    doc += `---\n\n`;
    
    // Repository Overview
    doc += this.generateRepositoryOverview(analysis.repositories);
    
    // Architecture Diagram
    doc += this.generateArchitectureDiagram(analysis);
    
    // Cross-Repository Dependencies
    doc += this.generateDependencySection(analysis.dependencies, analysis.repositories);
    
    // Shared Packages
    doc += this.generateSharedPackagesSection(analysis.sharedPackages);
    
    // Integration Patterns
    doc += this.generateIntegrationPatternsSection(analysis.integrationPatterns);
    
    // Tech Stack Summary
    doc += this.generateTechStackSummary(analysis.repositories);
    
    // Development Workflow
    doc += this.generateDevelopmentWorkflow(analysis);
    
    // Recommendations
    doc += this.generateRecommendations(analysis);
    
    // Footer
    doc += `---\n\n`;
    doc += `*Generated by repository-analyzer-mcp on ${currentDate}*\n`;
    
    return doc;
  }
  
  /**
   * Generate repository overview section
   */
  private generateRepositoryOverview(repos: Repository[]): string {
    let doc = `## 📦 Repository Overview\n\n`;
    
    doc += `| Repository | Type | Manifest Files |\n`;
    doc += `|------------|------|----------------|\n`;
    
    for (const repo of repos) {
      const manifests = [];
      if (repo.hasPackageJson) manifests.push('`package.json`');
      if (repo.hasPomXml) manifests.push('`pom.xml`');
      if (repo.hasBuildGradle) manifests.push('`build.gradle`');
      if (repo.hasRequirementsTxt) manifests.push('`requirements.txt`');
      
      doc += `| **${repo.name}** | ${repo.type} | ${manifests.join(', ')} |\n`;
    }
    
    doc += `\n`;
    return doc;
  }
  
  /**
   * Generate ASCII architecture diagram
   */
  private generateArchitectureDiagram(analysis: CrossRepoAnalysis): string {
    let doc = `## 🏗️ Architecture Diagram\n\n`;
    doc += `\`\`\`\n`;
    
    // Group repos by type
    const uiRepos = analysis.repositories.filter(r => r.hasPackageJson && r.name.includes('ui'));
    const serviceRepos = analysis.repositories.filter(r => r.hasPomXml || r.name.includes('service'));
    const otherRepos = analysis.repositories.filter(r => !uiRepos.includes(r) && !serviceRepos.includes(r));
    
    // Draw diagram
    if (uiRepos.length > 0) {
      doc += `┌─────────────────────────────────────┐\n`;
      doc += `│         Frontend Layer              │\n`;
      doc += `├─────────────────────────────────────┤\n`;
      for (const repo of uiRepos) {
        doc += `│  📱 ${repo.name.padEnd(30)} │\n`;
      }
      doc += `└─────────────────────────────────────┘\n`;
      doc += `              ↓ HTTP/REST\n`;
    }
    
    if (serviceRepos.length > 0) {
      doc += `┌─────────────────────────────────────┐\n`;
      doc += `│         Backend Layer               │\n`;
      doc += `├─────────────────────────────────────┤\n`;
      for (const repo of serviceRepos) {
        doc += `│  ⚙️  ${repo.name.padEnd(30)} │\n`;
      }
      doc += `└─────────────────────────────────────┘\n`;
    }
    
    if (otherRepos.length > 0) {
      doc += `              ↓\n`;
      doc += `┌─────────────────────────────────────┐\n`;
      doc += `│         Shared/Common               │\n`;
      doc += `├─────────────────────────────────────┤\n`;
      for (const repo of otherRepos) {
        doc += `│  📦 ${repo.name.padEnd(30)} │\n`;
      }
      doc += `└─────────────────────────────────────┘\n`;
    }
    
    doc += `\`\`\`\n\n`;
    return doc;
  }
  
  /**
   * Generate dependency flow section
   */
  private generateDependencySection(deps: CrossRepoDependency[], repos: Repository[]): string {
    let doc = `## 🔗 Cross-Repository Dependencies\n\n`;
    
    if (deps.length === 0) {
      doc += `No cross-repository dependencies detected.\n\n`;
      return doc;
    }
    
    doc += `### Dependency Flow\n\n`;
    doc += `| From Repository | To Repository | Package | Version | Type |\n`;
    doc += `|-----------------|---------------|---------|---------|------|\n`;
    
    for (const dep of deps) {
      const version = dep.version || 'N/A';
      doc += `| ${dep.fromRepo} | ${dep.toRepo} | \`${dep.packageName}\` | ${version} | ${dep.type} |\n`;
    }
    
    doc += `\n`;
    
    // Dependency graph
    doc += `### Dependency Graph\n\n`;
    doc += `\`\`\`mermaid\n`;
    doc += `graph LR\n`;
    
    for (const dep of deps) {
      doc += `  ${dep.fromRepo.replace(/-/g, '_')}[${dep.fromRepo}] -->|${dep.packageName}| ${dep.toRepo.replace(/-/g, '_')}[${dep.toRepo}]\n`;
    }
    
    doc += `\`\`\`\n\n`;
    
    return doc;
  }
  
  /**
   * Generate shared packages section
   */
  private generateSharedPackagesSection(sharedPackages: string[]): string {
    let doc = `## 📚 Shared Packages\n\n`;
    
    if (sharedPackages.length === 0) {
      doc += `No shared packages detected across repositories.\n\n`;
      return doc;
    }
    
    doc += `These packages are used by multiple repositories:\n\n`;
    
    for (const pkg of sharedPackages.slice(0, 20)) {
      doc += `- \`${pkg}\`\n`;
    }
    
    if (sharedPackages.length > 20) {
      doc += `\n*...and ${sharedPackages.length - 20} more*\n`;
    }
    
    doc += `\n**Recommendation:** Consider standardizing versions of shared packages across all repositories.\n\n`;
    
    return doc;
  }
  
  /**
   * Generate integration patterns section
   */
  private generateIntegrationPatternsSection(patterns: string[]): string {
    let doc = `## 🔄 Integration Patterns\n\n`;
    
    if (patterns.length === 0) {
      doc += `No common integration patterns detected.\n\n`;
      return doc;
    }
    
    doc += `Detected integration patterns across the workspace:\n\n`;
    
    for (const pattern of patterns) {
      doc += `- ✅ **${pattern}**\n`;
    }
    
    doc += `\n`;
    return doc;
  }
  
  /**
   * Generate tech stack summary
   */
  private generateTechStackSummary(repos: Repository[]): string {
    let doc = `## 🛠️ Tech Stack Summary\n\n`;
    
    const techStack = {
      frontend: new Set<string>(),
      backend: new Set<string>(),
      database: new Set<string>(),
      tools: new Set<string>()
    };
    
    // Categorize technologies
    for (const repo of repos) {
      if (repo.hasPackageJson) {
        techStack.frontend.add('Node.js/npm');
      }
      if (repo.hasPomXml) {
        techStack.backend.add('Java/Maven');
      }
      if (repo.hasBuildGradle) {
        techStack.backend.add('Java/Gradle');
      }
      if (repo.hasRequirementsTxt) {
        techStack.backend.add('Python/pip');
      }
    }
    
    doc += `| Category | Technologies |\n`;
    doc += `|----------|-------------|\n`;
    doc += `| **Frontend** | ${Array.from(techStack.frontend).join(', ') || 'None'} |\n`;
    doc += `| **Backend** | ${Array.from(techStack.backend).join(', ') || 'None'} |\n`;
    doc += `| **Database** | ${Array.from(techStack.database).join(', ') || 'To be detected'} |\n`;
    doc += `| **Tools** | ${Array.from(techStack.tools).join(', ') || 'To be detected'} |\n`;
    
    doc += `\n`;
    return doc;
  }
  
  /**
   * Generate development workflow section
   */
  private generateDevelopmentWorkflow(analysis: CrossRepoAnalysis): string {
    let doc = `## 👨‍💻 Development Workflow\n\n`;
    
    doc += `### Working Across Multiple Repositories\n\n`;
    doc += `1. **Clone all repositories:**\n`;
    doc += `   \`\`\`bash\n`;
    for (const repo of analysis.repositories) {
      doc += `   cd ${analysis.workspace}\n`;
      doc += `   # Clone ${repo.name}\n`;
    }
    doc += `   \`\`\`\n\n`;
    
    doc += `2. **Install dependencies:**\n`;
    doc += `   \`\`\`bash\n`;
    for (const repo of analysis.repositories) {
      if (repo.hasPackageJson) {
        doc += `   cd ${repo.name} && npm install\n`;
      } else if (repo.hasPomXml) {
        doc += `   cd ${repo.name} && mvn install\n`;
      }
    }
    doc += `   \`\`\`\n\n`;
    
    doc += `3. **Start development servers:**\n`;
    doc += `   - Follow individual repository README files for specific commands\n\n`;
    
    return doc;
  }
  
  /**
   * Generate recommendations section
   */
  private generateRecommendations(analysis: CrossRepoAnalysis): string {
    let doc = `## 💡 Recommendations\n\n`;
    
    doc += `### Where to Add New Features\n\n`;
    
    // Provide recommendations based on repo types
    const uiRepos = analysis.repositories.filter(r => r.hasPackageJson && r.name.includes('ui'));
    const serviceRepos = analysis.repositories.filter(r => r.hasPomXml || r.name.includes('service'));
    
    if (uiRepos.length > 0) {
      doc += `**Frontend Features:**\n`;
      for (const repo of uiRepos) {
        doc += `- Add UI components to \`${repo.name}\`\n`;
      }
      doc += `\n`;
    }
    
    if (serviceRepos.length > 0) {
      doc += `**Backend Features:**\n`;
      for (const repo of serviceRepos) {
        doc += `- Add business logic/APIs to \`${repo.name}\`\n`;
      }
      doc += `\n`;
    }
    
    doc += `### Best Practices\n\n`;
    doc += `- ✅ Keep shared dependencies in sync across repositories\n`;
    doc += `- ✅ Document cross-repo integration points\n`;
    doc += `- ✅ Use semantic versioning for internal packages\n`;
    doc += `- ✅ Maintain consistent code style across repos\n`;
    doc += `- ✅ Set up CI/CD pipelines for each repository\n\n`;
    
    return doc;
  }
}
